---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# R para Ciência de dados I

Repositório com o material do curso R para Ciência de Dados 1 ministrado em maio/junho de 2020.

## Slides

```{r, echo = FALSE}
knitr::kable(
  tibble::tibble(
    slide = list.files("slides/", pattern = ".html"),
    link = paste0("https://curso-r.github.io/202005-r4ds-1/slides/", slide)
  )
)
```

## Scripts

```{r, echo = FALSE}
knitr::kable(
  tibble::tibble(
    script = list.files("scripts/", pattern = ".R"),
    link = paste0("https://curso-r.github.io/202005-r4ds-1/scripts/", script)
  )
)
```

## Trabalhos vencedores

```{r}
knitr::kable(
  tibble::tibble(
    script = c(
      "trabalhos_vencedores//Desafio_flexdasboard.html",
      "trabalhos_vencedores/concursolouise.html",
      "trabalhos_vencedores/Projeto_Curso-R.html"
    ),
    link = paste0("https://curso-r.github.io/202005-r4ds-1/trabalhos_vencedores/", script)
  )
)
```

